### PR TITLE
fix invalid html

### PR DESCRIPTION
**Pull request by salvan13**
moved index.js script inside body

### CODE REVIEW

**Comment by lukejacksonn** [comment]
@salvan13 sorry this took a while to be addressed (I must have missed the notification).. personally I like `body` to be reserved as a container for the rendered `app` only. So I put the script tag after the body.. agreed it won't validate as such but it is nothing too much wrong with this pattern (https://stackoverflow.com/questions/3037725/is-it-wrong-to-place-the-script-tag-after-the-body-tag).

@Swizz has taken the _best of both worlds_ approach here and kept the body free of noise but ensured the script is executed only when the document has fully loaded by using `defer`. I shouls start to adopt such a habit 😅

**Comment by salvan13** [comment]
nice, I like @Swizz solution, it's much better :+1:

**Comment by JorgeBucaran** [comment]
@lukejacksonn I missed the notification too. For some reason I wasn't watching the repo, but now I am. You are not watching it either by the way.

**Comment by lukejacksonn** [comment]
@JorgeBucaran whoooops! Am now, thanks 🙇

**Comment by JorgeBucaran** [comment]
So, shall we close here? @salvan13

**Comment by Swizz** [comment]
A merge commit of #6 will close this one

**Pull request closed without merging**
